###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

thaliak-redis:
  image: phpdockerio/redis:latest
  container_name: thaliak-redis

thaliak-mysql:
  image: mysql:5.7
  container_name: thaliak-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=thaliak
    - MYSQL_USER=thaliak
    - MYSQL_PASSWORD=secret

thaliak-webserver:
  image: phpdockerio/nginx:latest
  container_name: thaliak-webserver
  volumes:
      - ./code:/var/www/thaliak
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  links:
   - thaliak-php-fpm

thaliak-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: thaliak-php-fpm
  volumes:
    - ./code:/var/www/thaliak
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - thaliak-mysql
    - thaliak-redis
